<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class EmpfohlenSetting {
	private $empfohlen_setting_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'empfohlen_setting_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'empfohlen_setting_page_init' ) );
	}

	public function empfohlen_setting_add_plugin_page() {
		
		add_menu_page(
			__('Empfohlen Dashboard', 'emp' ), 
			__('Empfohlen', 'emp' ), 
			'manage_options', // capability
			'empfohlen', // menu_slug
			array( $this, 'empfohlen_dashboard_admin_page' ), // function
			'dashicons-dashboard', // icon_url
			3 // position
		);

		add_submenu_page(
	        'empfohlen',
	        __( 'Empfohlen Setting', 'emp' ),
	        __( 'Empfohlen Setting', 'emp' ),
	        'manage_options',
	        'empfohlen-setting',
	        array( $this, 'empfohlen_setting_create_admin_page' )
    	);

		 
	}



	

	public function empfohlen_setting_create_admin_page() {
		$this->empfohlen_setting_options = get_option( 'empfohlen_setting_option_name' ); ?>

		<div class="wrap">
			<h2>Empfohlen Setting</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'empfohlen_setting_option_group' );
					do_settings_sections( 'empfohlen-setting-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function empfohlen_setting_page_init() {
		register_setting(
			'empfohlen_setting_option_group', // option_group
			'empfohlen_setting_option_name', // option_name
			array( $this, 'empfohlen_setting_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'empfohlen_setting_setting_section', // id
			'Settings', // title
			array( $this, 'empfohlen_setting_section_info' ), // callback
			'empfohlen-setting-admin' // page
		);

		add_settings_field(
			'auto_mail_0', // id
			'Auto Mail', // title
			array( $this, 'auto_mail_0_callback' ), // callback
			'empfohlen-setting-admin', // page
			'empfohlen_setting_setting_section' // section
		);

		add_settings_field(
			'auto_mail_description_1', // id
			'Auto Mail Description', // title
			array( $this, 'auto_mail_description_1_callback' ), // callback
			'empfohlen-setting-admin', // page
			'empfohlen_setting_setting_section' // section
		);

		add_settings_field(
			'currency_2', // id
			'Currency', // title
			array( $this, 'currency_2_callback' ), // callback
			'empfohlen-setting-admin', // page
			'empfohlen_setting_setting_section' // section
		);
	}

	public function empfohlen_setting_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['auto_mail_0'] ) ) {
			$sanitary_values['auto_mail_0'] = $input['auto_mail_0'];
		}

		if ( isset( $input['auto_mail_description_1'] ) ) {
			$sanitary_values['auto_mail_description_1'] = esc_textarea( $input['auto_mail_description_1'] );
		}

		if ( isset( $input['currency_2'] ) ) {
			$sanitary_values['currency_2'] = sanitize_text_field( $input['currency_2'] );
		}

		return $sanitary_values;
	}

	public function empfohlen_setting_section_info() {
		
	}

	public function auto_mail_0_callback() {
		printf(
			'<input type="checkbox" name="empfohlen_setting_option_name[auto_mail_0]" id="auto_mail_0" value="auto_mail_0" %s> <label for="auto_mail_0">Enable sending auto email to new user. </label>',
			( isset( $this->empfohlen_setting_options['auto_mail_0'] ) && $this->empfohlen_setting_options['auto_mail_0'] === 'auto_mail_0' ) ? 'checked' : ''
		);
	}

	public function auto_mail_description_1_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="empfohlen_setting_option_name[auto_mail_description_1]" id="auto_mail_description_1">%s</textarea>',
			isset( $this->empfohlen_setting_options['auto_mail_description_1'] ) ? esc_attr( $this->empfohlen_setting_options['auto_mail_description_1']) : ''
		);
	}

	public function currency_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="empfohlen_setting_option_name[currency_2]" id="currency_2" value="%s">',
			isset( $this->empfohlen_setting_options['currency_2'] ) ? esc_attr( $this->empfohlen_setting_options['currency_2']) : ''
		);
	}


	public function empfohlen_dashboard_admin_page(){ ?>

		<h1>This is Dashboard </h1>

	<?php
	}

}
if ( is_admin() )
	$empfohlen_setting = new EmpfohlenSetting();

/* 
 * Retrieve this value with:
 * $empfohlen_setting_options = get_option( 'empfohlen_setting_option_name' ); // Array of All Options
 * $auto_mail_0 = $empfohlen_setting_options['auto_mail_0']; // Auto Mail
 * $auto_mail_description_1 = $empfohlen_setting_options['auto_mail_description_1']; // Auto Mail Description
 * $currency_2 = $empfohlen_setting_options['currency_2']; // Currency
 */

